services:
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: MINIOROOT
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info
    depends_on:
      redis:
        condition: service_started
      minio:
        condition: service_healthy
        restart: true
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
    volumes:
      - .:/app